# docker/docker-compose.yml
version: '3.8'

services:
  client:
    build:
      context: ../client
      dockerfile: ../docker/client.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000

  server:
    build:
      context: ../server
      dockerfile: ../docker/server.Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../server:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/videodb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: